package Database.Entities;
// Generated Jul 17, 2018 3:35:48 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Claims generated by hbm2java
 */
public class Claims  implements java.io.Serializable {


     private Integer id;
     private Members members;
     private Date date;
     private String rationale;
     private String status;
     private float amount;

    public Claims() {
    }

    public Claims(Members members, Date date, String rationale, String status, float amount) {
       this.members = members;
       this.date = date;
       this.rationale = rationale;
       this.status = status;
       this.amount = amount;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Members getMembers() {
        return this.members;
    }
    
    public void setMembers(Members members) {
        this.members = members;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getRationale() {
        return this.rationale;
    }
    
    public void setRationale(String rationale) {
        this.rationale = rationale;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public float getAmount() {
        return this.amount;
    }
    
    public void setAmount(float amount) {
        this.amount = amount;
    }




}


