package Database.Entities;
// Generated Jul 17, 2018 3:35:48 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Members generated by hbm2java
 */
public class Members  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String address;
     private Date dob;
     private Date dor;
     private float balance;
     private Set paymentses = new HashSet(0);
     private Set claimses = new HashSet(0);
     private Set userses = new HashSet(0);

    public Members() {
    }

	
    public Members(float balance) {
        this.balance = balance;
    }
    public Members(String name, String address, Date dob, Date dor, float balance, Set paymentses, Set claimses, Set userses) {
       this.name = name;
       this.address = address;
       this.dob = dob;
       this.dor = dor;
       this.balance = balance;
       this.paymentses = paymentses;
       this.claimses = claimses;
       this.userses = userses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public Date getDor() {
        return this.dor;
    }
    
    public void setDor(Date dor) {
        this.dor = dor;
    }
    public float getBalance() {
        return this.balance;
    }
    
    public void setBalance(float balance) {
        this.balance = balance;
    }
    public Set getPaymentses() {
        return this.paymentses;
    }
    
    public void setPaymentses(Set paymentses) {
        this.paymentses = paymentses;
    }
    public Set getClaimses() {
        return this.claimses;
    }
    
    public void setClaimses(Set claimses) {
        this.claimses = claimses;
    }
    public Set getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set userses) {
        this.userses = userses;
    }




}


