package Database.Entities;
// Generated Jul 17, 2018 3:35:48 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Payments generated by hbm2java
 */
public class Payments  implements java.io.Serializable {


     private Integer id;
     private Members members;
     private String typeOfPayment;
     private float amount;
     private Date date;
     private Date time;

    public Payments() {
    }

    public Payments(Members members, String typeOfPayment, float amount, Date date, Date time) {
       this.members = members;
       this.typeOfPayment = typeOfPayment;
       this.amount = amount;
       this.date = date;
       this.time = time;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Members getMembers() {
        return this.members;
    }
    
    public void setMembers(Members members) {
        this.members = members;
    }
    public String getTypeOfPayment() {
        return this.typeOfPayment;
    }
    
    public void setTypeOfPayment(String typeOfPayment) {
        this.typeOfPayment = typeOfPayment;
    }
    public float getAmount() {
        return this.amount;
    }
    
    public void setAmount(float amount) {
        this.amount = amount;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


