package Database.Entities;
// Generated Jul 17, 2018 3:35:48 PM by Hibernate Tools 4.3.1



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer id;
     private Members members;
     private String password;
     private String status;
     private String username;
     private String usertype;

    public Users() {
    }

    public Users(Members members, String password, String status, String username, String usertype) {
       this.members = members;
       this.password = password;
       this.status = status;
       this.username = username;
       this.usertype = usertype;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Members getMembers() {
        return this.members;
    }
    
    public void setMembers(Members members) {
        this.members = members;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getUsertype() {
        return this.usertype;
    }
    
    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }




}


